reference: reference/ref.fa

# basic languages
java8: /home/users/cjyoon/tools/jdk1.8.0_171/bin/java
java7: /home/users/cjyoon/tools/jdk1.7.0_80/bin/java
python3: /home/users/cjyoon/anaconda3/bin/python
python2: /home/users/cjyoon/anaconda3/envs/py27/bin/python

# bam processing
picard: /home/users/tools/picard/dist/picard.jar
gatk: /home/users/cjyoon/tools/GenomeAnalysisTK-3.8-1/GenomeAnalysisTK.jar
samtools: /home/users/cjyoon/anaconda3/bin/samtools
bwa: /home/users/cjyoon/anaconda3/bin/bwa
knownindel: /home/users/data/02_annotation/01_GATK/01_golden_standard/Mills_and_1000G_gold_standard.indels.b37.vcf
dbsnp: /home/users/data/02_annotation/01_GATK/02_db_snp/dbsnp_138.b37.vcf
cosmic: /home/users/data/02_annotation/03_mutect/cosmic_v71_141209.vcf
dbsnp_mutect: /home/users/data/02_annotation/03_mutect/dbsnp_132_b37.leftAligned.vcf  
